login:
    path: /login
    defaults:
        _controller: MiniCMSBundle:Users:login

register:
    path: /register
    defaults:
        _controller: MiniCMSBundle:Users:register
    
login_check:
    path: /login_check
    
logout:
    path: /logout
