mini_cms_frontend_home:
    path: /
    defaults: 
        _controller: MiniCMSBundle:Frontend:home
        
mini_cms_frontend_view:
    path: /page/{title}
    defaults:
        _controller: MiniCMSBundle:Frontend:view
    requirements:
        title: \w+
        
mini_cms_backend_home:
    path: /admin/home
    defaults:
        _controller: MiniCMSBundle:Backend:home
        
mini_cms_backend_add:
    path: /admin/add
    defaults:
        _controller: MiniCMSBundle:Backend:add

mini_cms_backend_update:
    path: /admin/update/{title}
    defaults:
        _controller: MiniCMSBundle:Backend:update
    requirements:
        title: \w+
    
mini_cms_backend_delete:
    path: /admin/delete/{title}
    defaults:
        _controller: MiniCMSBundle:Backend:delete
    requirements:
        title: \w+