mini_cms_frontend_home:
    path: /
    defaults: 
        _controller: MiniCMSBundle:Frontend:home
        
mini_cms_frontend_view:
    path: /page/{category}/{slug}
    defaults:
        _controller: MiniCMSBundle:Frontend:view
             
mini_cms_backend_home:
    path: /admin/home
    defaults:
        _controller: MiniCMSBundle:Backend:home
        
mini_cms_backend_add:
    path: /admin/add
    defaults:
        _controller: MiniCMSBundle:Backend:add

mini_cms_backend_edit:
    path: /admin/edit/{slug}
    defaults:
        _controller: MiniCMSBundle:Backend:edit
    
mini_cms_backend_delete:
    path: /admin/delete/{slug}
    defaults:
        _controller: MiniCMSBundle:Backend:delete
        
mini_cms_backend_add_category:
    path: /admin/addCat
    defaults:
        _controller: MiniCMSBundle:Backend:addCategory

mini_cms_backend_list_versions:
    path: /admin/versions/{slug}
    defaults:
        _controller: MiniCMSBundle:Backend:listVersions
        
mini_cms_backend_view_version:
    path: /admin/view/{id}
    defaults:
        _controller: MiniCMSBundle:Backend:viewVersion