<?php

namespace MiniCMSBundle\Repository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get all versions of a page
	 * 
	 * @param string $slug
	 * @return array
	 */
	public function findBySlug($slug)
	{
		$query = $this->createQueryBuilder("a");
		
		$query
			->innerJoin('a.page', 'p')
			->addSelect('p')
			->where('p.slug = :slug')
			->setParameter('slug', $slug)
		;
		
		return $query->getQuery()->getArrayResult();
	}
	
	/**
	 * Get a version with its page
	 * 
	 * @param int $id
	 * @return mixed|NULL
	 */
	public function findOneByWithPage($id)
	{
		$query = $this->createQueryBuilder("v");
		
		$query
			->leftJoin('v.page', 'p')
			->addSelect('p')
			->where('v.id = :id')
			->setParameter('id', $id)
		;
		
		return $query->getQuery()->getOneOrNullResult();
	}
}
